services:
   php:
      container_name: jr-php
      build:
         context: .
         dockerfile: php.Dockerfile
      volumes:
         - ./src/:/var/www/html
         - ./php.ini:/usr/local/etc/php/conf.d/php.ini
         - vendor:/var/www/html/vendor
      depends_on:
         - composer
         - mysql
      stdin_open: true
      tty: true
   composer:
      image: composer:latest
      command: sh -c "composer install"
      working_dir: "/home"
      volumes:
         - ./src/composer.json:/home/composer.json
         - ./src/composer.lock:/home/composer.lock
         - vendor:/home/vendor
   mysql:
      image: mysql:latest
      restart: always
      container_name: mysql
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_PASSWORD: root
      volumes:
         - ./Dump.sql:/docker-entrypoint-initdb.d/dump.sql
   phpmyadmin:
      image: phpmyadmin:latest
      restart: always
      depends_on:
         - mysql
      container_name: jr-phpmyadmin
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: jeux_redige
         MYSQL_USER: root
         PMA_HOST: mysql
         PMA_ARBITRARY: 1

volumes:
   vendor:
   # mysql-data:
